WINDOW_NAME = "Graph Coloring"
WINDOW_HEIGHT = 600
WINDOW_WIDTH = 1200
WINDOW_X = 350
WINDOW_Y = 100
ICON_DIRECTION = "Files/icon.ico"
PHOTO_DIRECTION = "Files/Graph.png"
OUTPUT_FILE = "Files/output.txt"
SAVED_GRAPH = "Files/saved_graph.txt"
